import { Component } from '@angular/core';

@Component({
  selector: 'app-offer-your-property',
  templateUrl: './offer-your-property.component.html'
})
export class OfferYourPropertyComponent {

  Neighborhoods: string[] = [
    'ASTURIAS',
    'ALCAZARES',
    'PORTAL DE ALZACARES',
    'FRANCIAVILLA',
    'PILAR',
    'CHIPRE',
    'AQUILINO',
    'CAMPO HERMOSO',
    'LINARES',
    'CENTRO',
    'CASTELLANA',
    'PANORAMA',
    'ESTAMBUL',
    'CAMBULOS',
    'EL CARMELO',
    'EL GUAMAL',
    'VIVENTO',
    'ONDAS DEL OTÚN',
    'RESERVAS DEL BOSQUE',
    'NOGALES',
    'ZONA INDUSTRIAL',
    'LA ALHAMBRA',
    'BOSQUES DE LA ENEA',
    'ENEAS',
    'TEJARES',
    'SALTO DEL PERRO',
    'TREBOL',
    'SAN MARCEL',
    'FLORIDA',
    'VILLA CARMEN',
    'ZAPALMAR',
    'ALAMO',
    'EL PRADO',
    'CAMPIÑ',
    'BARRIO COLOMBIA',
    'CONFA DE LA 50',
    'PALOGRANDE',
    'ESTRELLA',
    'BELÉN',
    'VERSALLES',
    'ARBOLEDA',
    'AV PARALELA',
    'AV SANTANDER',
    'SAN JORGE',
    'LAS AMERICAS',
    'LOS CEDROS',
    'LEONORA',
    'ARGENTINA',
    'LOS ROSALES',
    'CASTILLA',
    'PALONEGRO',
    'CAROLA',
    'VILLA CAFÉ',
    'ALTOS DE GRANADA',
    'AV. DEL RÍO',
    'MINITAS',
    'LA CUMB',
    'RESULTAN',
    'ANIZAMI',
    'LANCERRO DE ORO',
    'ALTA SUIZA',
    'COLSEGUROS',
    'BELLA SUIZA',
    'SAN RAFAEL',
    'LAURELES',
    'LA RAMBLA',
    'PALERMO',
    'CAMELIA',
    'VIZCAYA',
    'GUAYACANES'
  ];

  business: string[] = [
    'Arrendamiento',
    'Venta',
    'Permuta'
  ];

}
